### ISSUE TITLE
Chat enhancements, Commands (feature/enhancements)

### ISSUE THREAD

**Issue by davidleebooth** [yro7/LLM-craft#2]
After tinkering for a couple evenings, I am loving this plugin. If you are good at constructing behavioral prompts in system and organizing background information these npc's can prove rather useful while being flavorful to the server environment. If you are taking in feature suggestions I have a few ideas to share.

NPC specific system prompt that is appended or prepended to the models system prompt config could look like:
```
models:
  Guard: 
    system-prompt: "You patrol the city... give directions to the following locations... etc,
  ...
npcs:
  GaryGuard:
    model: Guard
    npc-system-append: "Nothing seems to get you down, new to the job you are encouraging and encourage-able... 
  OldRick:
    model: Guard
    npc-system-append: "You are three years from retirement, you are friendly, but old-fashioned and quick to temper if folks start messing around...
```

I am also curious if being able to "whisper" NPC's could be possible? I could see on a server with a few models and a handful of players the public chat getting a little awkward.

"i" to interact
pressing a key such as i while looking at the npc within its radius to engage the NPC messaging system could cut down errant chatter while still being able to have more than one npc and player engaging each other in say a tavern

A funny thing I have done is play on how information in llm chats falls off as the conversations go on, instructing that when asked the model can give a quest that can be completed within the game mechanics of modern minecraft, but when they come back completing the quest pretend that you never sent them on it and tell them something like the journey is the reward or equivalent.

It may not be that far off to be able to let models reward players, hand out bread, offer teleports to locations/worlds if a model could have an allow-list of commands and intents, perhaps some async background requests when enabled so when an intent is matched a command may be run after the chat response.

```
models:
  MageTaxi:
    cmd: yes // this enables requests to the llm to match if the players intents trigger a command this also appends the system prompt informing the agent background functions will complete players requests
    allow-list:
      command1: "/tp {player} 0 72 0"
      intent1: "when the player wants to go to spawn"

  LunchLady:
    cmd: yes
    cooldown: 90
    allow-list:
      command1: "/give {player} minecraft:apple 1"
      intent1: "one of the foods you may give the player if they say they are hungry or ask you for something to eat."
      command2: "/give {player} minecraft:bread 1"
      intent2: "one of the foods you may give the player if they say they are hungry or ask you for something to eat."
```

anyhow, excellent work and a fun plugin to use already.

**Comment by yro7** [comment]
Hey,

The NPC specific prompt is a great idea! You already can achieve a similar result by defining a model-type for each npc, your example would look like this : 

```
models:
  GuardGary: 
    system-prompt: "You patrol the city... give directions to the following locations... etc. Nothing seems to get you down, new to the job you are encouraging and encourage-able... "
  GuardOldRick:
    model: OldRick
    npc-system-append: "You patrol the city... give directions to the following locations... etc. You are three years from retirement, you are friendly, but old-fashioned and quick to temper if folks start messing around..."

npcs:
  GaryGuard:
    model: GuardGary
  OldRick:
    model: GuardOldRick
```

However, I reckon that this method is repetitive, even more if you have a more complex (and long) configuration for the "base" modeltype of Guards.

I'm keeping that idea and might implement it if I find the time to do it.

As for private npc : 
> I am also curious if being able to "whisper" NPC's could be possible? I could see on a server with a few models and a handful of players the public chat getting a little awkward.

You can do it ! In config.yml, it's what the field `visibility` in `models` is used for.

For example,

```
models:
  helper:
    provider: openai
    visibility: private
    persistent: true
    prefix: "§6§lHelper > §e"
    system-prompt: "You are a Minecraft helper, helping people when they ask you question."

npcs:
  helper:
    citizen-id: 1
    model: helper
    type: personal
    talking: chat
    range: 15
    message-only-in-range: true
```

Since the model-type Helper has a **private** visibility, only the player that triggered the NPC will see it's response, and others players won't see the message that the player sent.


About allowing models to use actions, it's actually a pretty hard thing to do right. LLMs are not designed to perform actions. I guess we could achieve this by telling the model to generate some "EXECUTE COMMAND n°" tokens but it would be really really easy to mess this up and create dupe exploits. For now, I won't implement this.

**Comment by davidleebooth** [comment]
Im glad the NPC specific appending or prepending the model system prompt is worth throwing into this eventually, It could be very dynamic especially if you see the same NPC character, but in different places in the world. So you can talk to the same Bob, but he's in both "north-town" and "eastville" with varying details between the two which are actually different NPCs in the back.

> You can do it ! In config.yml, it's what the field visibility in models is used for.

ahh, thanks for clarifying that on the server no one sees the message, is it the radius that mutes players inputs from general chat when set to private?

I am also curious about if/how resets work the groups usage limitations is it per group, per player? could there be room in the config to set some reset parameters? I know of ecommerce to MC command plugins. some options there could open up donations to reset/add to chat limits.

Oh, and once my server is done I should have some clips to link to for a spigotMC review.  makes spawn way more entertaining.

**Comment by yro7** [comment]
> ahh, thanks for clarifying that on the server no one sees the message, is it the radius that mutes players inputs from general chat when set to private?

That's it :) When a player sends a message within the radius of a private NPC, the message won't be displayed to others players.
If I recall correctly, if the model visibility is set to public but the NPC has message-only-in-range set to true, only players within the range parameters will see the message.

> I am also curious about if/how resets work the groups usage limitations is it per group, per player? could there be room in the config to set some reset parameters? I know of ecommerce to MC command plugins. some options there could open up donations to reset/add to chat limits.

The plugins hooks onto [LuckPerms](https://luckperms.net/wiki/Developer-API) which is the group/permission plugin manager that I use on my server (and that most paper spigot servers use). 

```
usage-limits:
  city-guard:
    deny-message: "You can not enter this castle."
    groups:
      default: 10
      vip: 20
  helper:
    deny-message: "I don't have anything to learn you anymore, good game !"
    groups:
      vip: 0
```

The limitations/usages of each player are reset each time the plugins is reloaded (it's meant to be a per-day limitations, since most servers do restart every day).

If a player has multiple groups, it's limit will be the highest of all it's groups :

```
    /**
     * Player limit is set as the max limit of all their group's limits.
     */
    public int maxUsage(CommandSender sender){
        return this.limits.keySet().stream()
                .filter(g -> sender.hasPermission("group."+g.getName()))
                .mapToInt(g -> this.getLimits().get(g))
                .max()
                .orElse(-1);
    }
```

**Comment by yro7** [comment]
Hey,

I added the system-append feature!

Here's an example:

```
models:
  city-guard:
    provider: openai
    model-name: gpt-3.5-turbo
    system-prompt: "You are the guard of a Minecraft city."
    visibility: public
    prefix: "§6§lGuard > §e"
    temperature: 2
    frequency-penalty: 1
npcs:
  guardEast:
    citizen-id: 0
    model: city-guard
    system-append: "You're from the poor east part of the city. You are kind and greetful."
  guardWest:
    citizen-id: 1
    model: city-guard
    system-append: "You're from the west part of the city. Everyone seems to bother you, you hate everyone. "
```

And this is the difference between the 2 models in game (using the console) : 

```
>ask npc-guardEast-global hey, what's up ?
[22:04:50 INFO]: Guard: Oh, hello there! Not much, just keeping an eye on things in the city. How can I help you today?

>ask npc-guardWest-global hey, what's up ?
[22:04:54 INFO]: Ugh, not you again. What do you want now?

```
